name: "Build And Release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-latest, ubuntu-latest, windows-latest]
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev

      - name: Install app dependencies
        run: cargo install cargo-bundle

      - name: Build the app
        run: cargo bundle --release

      - name: Zip App
        run: mv "target/release/bundle/osx/Tetrs.app" . && zip -r tetrs-mac.zip "Tetrs.app"

      # - name: Publish ubuntu files
      #   uses: softprops/action-gh-release@v1
      #   if: matrix.platform == 'ubuntu-latest'
      #   with:
      #     files: |
      #       target/release/bundle/*/*.deb

      # - name: Publish mac files
      #   uses: softprops/action-gh-release@v1
      #   if: matrix.platform == 'macos-latest'
      #   with:
      #     files: |
      #       tetrs-mac.zip

      # - name: Publish windows files
      #   uses: softprops/action-gh-release@v1
      #   if: matrix.platform == 'windows-latest'
      #   with:
      #     files: |
      #       target/release/bundle//*